-- mer-schema.sql — het `mer`-schema voor OCD-Postgres (mer-register.nl).
-- Zie ../docs/ocd-schema-voorstel.md voor de onderbouwing.
--
-- Sleutel-correctie na het laden van de praktijk (2026-07-17): `project` wordt
-- gesleuteld op `slug` (de Commissie-URL-slug — altijd aanwezig en uniek), met
-- `project_nr` als nullable UNIQUE kolom. Reden: niet elk Commissie-project heeft
-- PDF's en dus een projectnummer. Dit spiegelt de harvest-store (schema_sqlite.sql)
-- 1-op-1. Verwijzingen naar core.bronhouder/vth.etl_run zijn kolommen (nullable),
-- geen harde constraint — bronhouder_code wordt door resolve_bronhouder.py gevuld
-- (naam-match op core.bronhouder.overheidscode; ~72% event / ~75% project gedekt,
-- de rest = Rijk/ministeries/parlement/buitenland die niet in core.bronhouder staan).

CREATE SCHEMA IF NOT EXISTS mer;

-- Kanaal A — MER-proces-events uit KOOP SRU
CREATE TABLE IF NOT EXISTS mer.event (
    koop_id            text PRIMARY KEY,
    titel              text NOT NULL,
    datum_publicatie   date,
    publicatieblad     text,
    bevoegd_gezag_naam text,
    bronhouder_code    text,             -- -> core.bronhouder.overheidscode (resolve_bronhouder.py)
    event_type         text,             -- afgeleid
    instrument         text,             -- afgeleid
    subject_taxonomie  text,
    url                text,
    inhoud_tekst       text,
    raw_xml            text,
    ingest_run_id      integer,          -- -> vth.etl_run
    datum_ingest       timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_mer_event_datum      ON mer.event (datum_publicatie DESC);
CREATE INDEX IF NOT EXISTS idx_mer_event_type       ON mer.event (event_type);
CREATE INDEX IF NOT EXISTS idx_mer_event_instrument ON mer.event (instrument);
CREATE INDEX IF NOT EXISTS idx_mer_event_bg         ON mer.event (bevoegd_gezag_naam);
CREATE INDEX IF NOT EXISTS idx_mer_event_titel_fts  ON mer.event USING gin (to_tsvector('dutch', titel));

-- Kanaal B — Commissie m.e.r.-projecten
CREATE TABLE IF NOT EXISTS mer.project (
    slug             text PRIMARY KEY,
    project_nr       integer UNIQUE,
    titel            text NOT NULL,
    bevoegd_gezag    text,
    bronhouder_code  text,             -- -> core.bronhouder.overheidscode (resolve_bronhouder.py)
    initiatiefnemer  text,
    start_advisering date,
    advies_type      text,
    instrument       text,              -- afgeleid (meerderheid events, anders projecttitel)
    provincie        text,              -- afgeleid via PDOK-geocode
    lat              double precision,
    lon              double precision,
    url              text,
    lastmod          timestamptz,
    datum_ingest     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_mer_project_bg        ON mer.project (bevoegd_gezag);
CREATE INDEX IF NOT EXISTS idx_mer_project_prov      ON mer.project (provincie);
CREATE INDEX IF NOT EXISTS idx_mer_project_titel_fts ON mer.project USING gin (to_tsvector('dutch', titel));

-- Kanaal B — documenten (PDF's blijven extern; alleen metadata + URL)
CREATE TABLE IF NOT EXISTS mer.document (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_slug  text NOT NULL REFERENCES mer.project (slug) ON DELETE CASCADE,
    soort         text,
    bestandsnaam  text,
    url           text NOT NULL,
    mirror_url    text,
    datum_ingest  timestamptz NOT NULL DEFAULT now(),
    UNIQUE (project_slug, bestandsnaam)
);
CREATE INDEX IF NOT EXISTS idx_mer_document_project ON mer.document (project_slug);
CREATE INDEX IF NOT EXISTS idx_mer_document_soort   ON mer.document (soort);

-- Koppeling A <-> B
CREATE TABLE IF NOT EXISTS mer.project_event_link (
    project_slug  text NOT NULL REFERENCES mer.project (slug) ON DELETE CASCADE,
    koop_id       text NOT NULL REFERENCES mer.event   (koop_id) ON DELETE CASCADE,
    match_methode text,
    zekerheid     numeric(3,2),
    datum_ingest  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (project_slug, koop_id)
);

-- Kanaal C (optioneel) — link-oogst uit besluit-XML
CREATE TABLE IF NOT EXISTS mer.besluit_extref (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    besluit_work  text NOT NULL,
    extref_url    text NOT NULL,
    doel_soort    text,
    datum_ingest  timestamptz NOT NULL DEFAULT now(),
    UNIQUE (besluit_work, extref_url)
);
